### ISSUE TITLE
Area of Triangle produces invalid triangles

### ISSUE THREAD

**Issue by rolfvandekrol** [lukew3/mathgenerator#393]
### Bug Description

The 'Area of Triangle' generator came up with the triangle `17 19 1` (or in a different order, i'm not sure), which is of course not a real triangle. The answer, according to the generator was some answer involving `j`, but it seems like a bug to me that this generator make non-real triangles.

**Comment by rolfvandekrol** [comment]
I don't know the details of how the generators work, but a test to know if the triangle is real might be: add up the two lowest numbers, if the result is lower than the remaining (highest) number, it's not a real triangle.

**Comment by jsun1590** [comment]
Hi there, I believe this was fixed around a year ago in [Pull 361](https://github.com/lukew3/mathgenerator/pull/361). I just tested and the function seems to work as expected locally. I had a look at the gh-pages branch and it just appears that the statically generated data there is not updated.

**Comment by lukew3** [comment]
> Hi there, I believe this was fixed around a year ago in [Pull 361](https://github.com/lukew3/mathgenerator/pull/361). I just tested and the function seems to work as expected locally. I had a look at the gh-pages branch and it just appears that the statically generated data there is not updated.

Thanks, I thought this might be the case. #394 will prevent this from occurring in the future.

**Comment by rolfvandekrol** [comment]
![Screenshot 2022-12-19 at 08 57 49](https://user-images.githubusercontent.com/434397/208375516-370099bb-99ce-4282-9264-04d8ff84d78d.png)

Well, currently, this still happens on the github pages site.

**Comment by rolfvandekrol** [comment]
Ah, I misread the #394 . It's not a merged PR, but an issue to fix :)
